[agent]
  hostname = "telegraf-01"

[[inputs.snmp]]
  agents = ["ceos-01"]
  version = 2
  community = "${SNMP_COMMUNITY}"
  interval = "60s"
  timeout = "10s"
  retries = 3

  [[inputs.snmp.table]]
    name = "interface"

    [[inputs.snmp.table.field]]
      oid = "IF-MIB::ifDescr"
      is_tag = true

    [[inputs.snmp.table.field]]
      oid = "IF-MIB::ifHCInOctets"

    [[inputs.snmp.table.field]]
      oid = "IF-MIB::ifHCOutOctets"

[[outputs.file]]
  files = ["stdout"]