---
global:
  resolve_timeout: 5m

route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 12h
  receiver: 'default-receiver'
  routes:
      - matchers:
          - alertname="PeerInterfaceFlapping"
        receiver: 'webhook-receiver'

receivers:
  - name: 'default-receiver'
    # Add configurations for the default receiver here if needed

  - name: 'webhook-receiver'
    webhook_configs:
      - url: 'http://webhook:9997/v1/api/webhook'
        send_resolved: true