auth_enabled: false

server:
  http_listen_port: 3001

common:
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: inmemory
  replication_factor: 1
  path_prefix: /tmp/loki

query_range:
  results_cache:
    cache:
      embedded_cache:
        enabled: true
        max_size_mb: 100

schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

compactor:
  compaction_interval: 10m
  retention_enabled: true
  retention_delete_delay: 2h
  retention_delete_worker_count: 150

limits_config:
  reject_old_samples: true
  reject_old_samples_max_age: 168h

ruler:
  storage:
    type: local
    local:
      directory: /loki/rules
  rule_path: /loki/rules-temp
  alertmanager_url: http://alertmanager:9093
  ring:
    kvstore:
      store: inmemory
  enable_api: true

analytics:
 reporting_enabled: false

# ingester:
#   lifecycler:
#     address: 127.0.0.1
#     ring:
#       kvstore:
#         store: inmemory
#       replication_factor: 1
#     final_sleep: 0s
#   chunk_idle_period: 1h       # Any chunk not receiving new logs in this time will be flushed
#   max_chunk_age: 1h           # All chunks will be flushed when they hit this age, default is 1h
#   chunk_target_size: 1048576  # Loki will attempt to build chunks up to 1.5MB, flushing first if chunk_idle_period or max_chunk_age is reached first
#   chunk_retain_period: 30s    # Must be greater than index read cache TTL if using an index cache (Default index read cache TTL is 5m)
#   max_transfer_retries: 0     # Chunk transfers disabled
#   wal:
#     enabled: true
#     dir: /loki/wal