[agent]
  # Set the hostname because by default it will grab the container ID
  hostname = "telegraf-01"

[[inputs.snmp]]
  # Targets for the SNMP Plugin
  agents = ["ceos-01"]
  # SNMP version to use (v2)
  version = 2
  # SNMP community string passed as an environment variable - see example.env
  community = "${SNMP_COMMUNITY}"
  # SNMP polling interval, timeout and retries
  interval = "60s"
  timeout = "10s"
  retries = 3

  # Example of SNMP Get operation
  [[inputs.snmp.field]]
    # Overriding the name of the metric collected to "uptime"
    name = "uptime"
    # SNMP OID RFC1213-MIB::sysUpTime.0
    oid = "1.3.6.1.2.1.1.3.0"

  # Example of SNMP Walk operation
  [[inputs.snmp.table]]
    # Name of the metrics collected
    name = "interface"

    # Example of retrieving an specific field from the table
    [[inputs.snmp.table.field]]
      # Overriding the name of this field
      name = "name"
      # SNMP OID which has the Interface Name IF-MIB::ifDescr
      oid = "1.3.6.1.2.1.2.2.1.2"
      # Flag that signal to use this as a tag instead of a metric value
      is_tag = true

    # By default the plugin is collecting all the metrics from the table walk
    # but in this case we are selecting some specific fields to showcase in the book
    [[inputs.snmp.table.field]]
          name = "in_octets"
          # SNMP OID IF-MIB::ifHCInOctets
          oid = "1.3.6.1.2.1.31.1.1.1.6"

      [[inputs.snmp.table.field]]
          name = "out_octets"
          # SNMP OID IF-MIB::ifHCOutOctets
          oid = "1.3.6.1.2.1.31.1.1.1.10"

[[inputs.ping]]
  # Interval time between ping commands
  interval = "10s"
  # Number of ping packets to send per interval
  count = 3
  # Time to wait between sending ping packets in seconds
  ping_interval = 1.0
  # Time to wait for a ping response in seconds
  timeout = 5.0
  # Hosts to send ping packets to
  urls = ["ceos-01"]

# Outputs metrics to stdout
[[outputs.file]]
  files = ["stdout"]