---
groups:
  - name: Peer Interface Down
    rules:
      - alert: PeerInterfaceDown
        expr: interface_oper_status{intf_role="peer"} == 2
        for: 1m
        labels:
          severity: warning
          source: stack
          environment: network-observability-lab
          metric_name: interface_oper_status
          device: '{{ $labels.device }}'
          device_role: '{{ $labels.device_role }}'
          site: '{{ $labels.site }}'
          region: '{{ $labels.region }}'
          instance: '{{ $labels.host }}'
          device_platform: '{{ $labels.device_platform }}_{{ $labels.net_os }}'
        annotations:
          summary: "[NET] Device {{ $labels.device }}: Interface Uplink {{ $labels.name }} is down"
          description: "Interface {{ $labels.name }} on device {{ $labels.device }} is down!"

  - name: BGP Neighbor Down
    rules:
      - alert: BGPNeighborDown
        expr: bgp_neighbor_state == 2
        for: 1m
        labels:
          severity: critical
          source: stack
          environment: network-observability-lab
          metric_name: bgp_neighbor_state
          device: '{{ $labels.device }}'
          device_role: '{{ $labels.device_role }}'
          site: '{{ $labels.site }}'
          region: '{{ $labels.region }}'
          instance: '{{ $labels.host }}'
          device_platform: '{{ $labels.device_platform }}_{{ $labels.net_os }}'
        annotations:
          summary: "[NET] Device {{ $labels.device }}: BGP Neighbor {{ $labels.neighbor }}:{{ $labels.neighbor_asn }} is down"
          description: "BGP Neighbor towards {{ $labels.neighbor }}:{{ $labels.neighbor_asn }} on device {{ $labels.device }} is down!"
