---
networks:
  network-observability:
    external: true
    name: network-observability

services:

  telegraf-01:
    build:
      dockerfile: "./telegraf/telegraf.Dockerfile"
      args:
        TELEGRAF_IMAGE: ${TELEGRAF_IMAGE:-docker.io/telegraf:1.31}
    command: telegraf --config /etc/telegraf/telegraf.conf
    tty: true
    volumes:
      - ./telegraf/telegraf-01.conf.toml:/etc/telegraf/telegraf.conf
    ports:
      - 9004:9004
    env_file:
      - ../../.env
    networks:
      - network-observability

  telegraf-02:
    build:
      dockerfile: "./telegraf/telegraf.Dockerfile"
      args:
        TELEGRAF_IMAGE: ${TELEGRAF_IMAGE:-docker.io/telegraf:1.31}
    command: telegraf --config /etc/telegraf/telegraf.conf
    tty: true
    volumes:
      - ./telegraf/telegraf-02.conf.toml:/etc/telegraf/telegraf.conf
      - ./telegraf/script.py:/etc/telegraf/script.py
    ports:
      - 9005:9005
    env_file:
      - ../../.env
    networks:
      - network-observability

  logstash:
    image: ${LOGSTASH_LOKI_IMAGE:-docker.io/grafana/logstash-output-loki:main}
    command: -f /home/logstash/logstash.cfg
    volumes:
      - ./logstash/logstash.cfg:/home/logstash/logstash.cfg
    ports:
      - 1515:1515
    environment:
      XPACK_MONITORING_ENABLED: false
    env_file:
      - ../../.env
    networks:
      - network-observability
