---
groups:
  - name: network_traffic_overview
    rules:
    - record: device:network_traffic_in_bps:rate_2m
      expr: sum(rate(interface_in_octets[2m])) by (device) * 8
    - record: device:network_traffic_out_bps:rate_2m
      expr: sum(rate(interface_out_octets[2m])) by (device) * 8


  - name: BGP Interface Flaps
    rules:
      - alert: InterfaceUplinkFlaps
        expr: changes(interface_oper_status{device=~"fr-border.*", interface_label="uplink"}[2m]) > 0
        for: 1m
        labels:
          severity: warning
          source: stack
          environment: Production
          metric_name: interface_oper_status
          device: "{{ $labels.device }}"
          device_role: "{{ $labels.device_role }}"
          site: "{{ $labels.site }}"
          region: "{{ $labels.region }}"
          instance: "{{ $labels.host }}"
          device_platform: "{{ $labels.device_platform }}_{{ $labels.net_os }}"
          policy_kind: "interface_flaps"
          policy_entity: "bgp_peer"
          policy_action: "tshift"
        annotations:
          summary: "Interface Uplink Flaps detected"
          description: "Device {{ $labels.device }} interface {{ $labels.interface }} is flapping!"
