[agent]
  hostname = "telegraf-02"

###############################################################################
#                            DATA COLLECTION                                  #
###############################################################################
[[inputs.snmp]]
  agents = ["ceos-02"]
  version = 2
  community = "${SNMP_COMMUNITY}"
  interval = "60s"
  timeout = "10s"
  retries = 3

  [inputs.snmp.tags]
    collection_type = "snmp"

  # `up` measurement
  [[inputs.snmp.field]]
    name = "uptime"
    oid = "RFC1213-MIB::sysUpTime.0"

[[inputs.gnmi]]
  addresses = ["ceos-02:50051"]
  username = "${NETWORK_AGENT_USER}"
  password = "${NETWORK_AGENT_PASSWORD}"
  redial = "20s"
  # Exclude the "path" tag from the output
  tagexclude = ["path"]

  [inputs.gnmi.tags]
    collection_type = "gnmi"

  [[inputs.gnmi.subscription]]
    name = "interface"
    path = "/interfaces/interface/state/counters"
    subscription_mode = "sample"
    sample_interval = "10s"

  [[inputs.gnmi.subscription]]
    name = "interface"
    path = "/interfaces/interface/state/oper-status"
    subscription_mode = "sample"
    sample_interval = "10s"

  [[inputs.gnmi.subscription]]
    name = "interface"
    path = "/interfaces/interface/state/admin-status"
    subscription_mode = "sample"
    sample_interval = "10s"


[[inputs.exec]]
  commands = ["python /etc/telegraf/bgp_collector.py arista_eos ceos-02"]
  interval = "20s"
  timeout = "5s"
  data_format = "influx"
##############################################################################
#                            DATA NORMALIZATION                              #
##############################################################################
[[processors.rename]]
  [[processors.rename.tagpass]]
    collection_type = ["gnmi"]
  # Rename the tag "source" to "device"
  [[processors.rename.replace]]
    tag = "source"
    dest = "device"
  [[processors.rename.replace]]
    field = "in_errors"
    dest = "in_errors_pkts"
  [[processors.rename.replace]]
    field = "out_errors"
    dest = "out_errors_pkts"
  [[processors.rename.replace]]
    field = "in_discards"
    dest = "in_discards_pkts"
  [[processors.rename.replace]]
    field = "out_discards"
    dest = "out_discards_pkts"


[[processors.rename]]
  [[processors.rename.tagpass]]
    collection_type = ["snmp"]
  # Rename the tag "agent_host" to "device"
  [[processors.rename.replace]]
    tag = "agent_host"
    dest = "device"

  # Rename the measurement "snmp" to "device"
  [[processors.rename.replace]]
    measurement = "snmp"
    dest = "device"

# Enum processor for interface oper_status and admin_status field values to numbers
[[processors.enum]]
  namepass = ["interface"]

  [[processors.enum.tagpass]]
    collection_type = ["snmp", "gnmi"]

  [[processors.enum.mapping]]
    ## Name of the field to map
    field = "oper_status"
    [processors.enum.mapping.value_mappings]
      UP = 1
      DOWN = 2
      TESTING = 3
      UNKNOWN = 4
      DORMANT = 5
      NOT_PRESENT = 6
      LOWER_LAYER_DOWN = 7

  [[processors.enum.mapping]]
    field = "admin_status"
    [processors.enum.mapping.value_mappings]
      UP = 1
      DOWN = 2
      TESTING = 3

###############################################################################
#                            DATA ENRICHMENT                                  #
###############################################################################
[[processors.regex]]
  namepass = ["interface"]

  [processors.regex.tagpass]
      device = ["ceos-02"]

  [[processors.regex.tags]]
    key = "name"
    pattern = "^Ethernet.*$"
    result_key = "intf_role"
    replacement = "peer"

  [[processors.regex.tags]]
    key = "name"
    pattern = "^Management.*$"
    result_key = "intf_role"
    replacement = "mgmt"


##############################################################################
#                            DATA OUTPUT                                     #
##############################################################################
[[outputs.file]]
  files = ["stdout"]