---
networks:
  network-observability:
    external: true
    name: network-observability

version: "3.8"
services:

  telegraf-01:
    image: docker.io/networktocode/network-agent:1.27-py3.8-v0.4.2-v0.3.10
    command: telegraf --config /etc/telegraf/telegraf.conf
    tty: true
    volumes:
      - ./configs/telegraf/telegraf-01.conf.toml:/etc/telegraf/telegraf.conf
    ports:
      - 9004:9004
    env_file:
      - ../../.env
    networks:
      - network-observability

  telegraf-02:
    image: docker.io/networktocode/network-agent:1.27-py3.8-v0.4.2-v0.3.10
    command: telegraf --config /etc/telegraf/telegraf.conf
    tty: true
    volumes:
      - ./configs/telegraf/telegraf-02.conf.toml:/etc/telegraf/telegraf.conf
      - ./configs/telegraf/script.py:/etc/telegraf/script.py
    ports:
      - 9005:9005
    env_file:
      - ../../.env
    networks:
      - network-observability

  logstash:
    image: docker.io/grafana/logstash-output-loki:main
    command: -f /home/logstash/logstash.cfg
    volumes:
      - ./configs/logstash/logstash.cfg:/home/logstash/logstash.cfg
    ports:
      - 1515:1515
    environment:
      XPACK_MONITORING_ENABLED: false
    env_file:
      - ../../.env
    networks:
      - network-observability
