---
apiVersion: 1

datasources:
- name: prometheus
  type: prometheus
  url: http://prometheus:9090
- name: loki
  type: loki
  url: http://loki:3001
- name: nautobot
  type: fifemon-graphql-datasource
  url: http://nautobot:8080/api/graphql/
  editable: true
  jsonData:
    httpHeaderName1: Authorization
  secureJsonData:
    httpHeaderValue1: Token ${NAUTOBOT_SUPERUSER_API_TOKEN}
- name: infinity
  type: yesoreyeram-infinity-datasource
  editable: true