---
# Global Settings for Alertmanager
global:
  # Time after which an alert is declared resolved (good for demo purposes)
  resolve_timeout: 30m

# Route tree for Alertmanager
route:
  # Default receiver for alerts
  receiver: "keep"         # Name of the receiver to send alerts to
  group_by: ['alertname']  # Group alerts by alertname
  group_wait:      15s     # Wait 15 seconds to group alerts
  group_interval:  15s     # Send all alerts as a batch every 15 seconds
  repeat_interval: 1m      # Repeat notifications every 1 minute

# Receivers for Alertmanager
receivers:
# Receiver for sending alerts to Keep
- name: "keep"
  # Webhook configuration for Keep
  webhook_configs:
  - url: 'https://api.keephq.dev/alerts/event/prometheus'  # URL for the Keep API
    send_resolved: true               # Send resolved alerts
    http_config:                      # HTTP configuration for the webhook
      basic_auth:                     # Basic authentication for the webhook
        username: api_key             # Username for the webhook
        password_file: keep_api_key   # Password file for the webhook
