[tool.poetry]
name = "examples"
version = "0.1.0"
description = ""
authors = ["NetObs"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
ansible = "^9.3.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
