[global_tags]
  environment = "${ENVIRONMENT}"

[agent]
  hostname = "telegraf-01"

# Performs a TCP handshake to the specified TCP address.
[[inputs.net_response]]
  protocol = "tcp"
  address = "ceos-01:22"

# Outputs metrics to stdout
[[outputs.file]]
  files = ["stdout"]

# Outputs prometheus formatted metrics to endpoint /metrics
[[outputs.prometheus_client]]
  listen = ":9004"
  metric_version = 2
