[agent]
 hostname = "telegraf-02"


[[inputs.gnmi]]
 addresses = ["ceos-02:50051"]
 username = "${NETWORK_AGENT_USER}"
 password = "${NETWORK_AGENT_PASSWORD}"
 redial = "20s"


 [[inputs.gnmi.subscription]]
   name = "interface"
   path = "/interfaces/interface/state/counters"
   subscription_mode = "sample"
   sample_interval = "10s"


 [[inputs.gnmi.subscription]]
   name = "interface"
   path = "/interfaces/interface/state/oper-status"
   subscription_mode = "sample"
   sample_interval = "10s"


[[outputs.file]]
 files = ["stdout"]
