[agent]
 hostname = "telegraf-01"


[[inputs.snmp]]
 agents = ["ceos-01"]
 version = 2
 community = "${SNMP_COMMUNITY}"
 interval = "60s"
 timeout = "10s"
 retries = 3


 [[inputs.snmp.table]]
   name = "interface"


   [[inputs.snmp.table.field]]
     # IF-MIB::ifDescr
     oid = "1.3.6.1.2.1.2.2.1.2"
     is_tag = true


   [[inputs.snmp.table.field]]
     # IF-MIB::ifHCInOctets
     oid = "1.3.6.1.2.1.31.1.1.1.6"


   [[inputs.snmp.table.field]]
     # IF-MIB::ifHCOutOctets
     oid = "1.3.6.1.2.1.31.1.1.1.10"


[[outputs.file]]
 files = ["stdout"]
