[agent]
  hostname = "telegraf-02"

[[inputs.gnmi]]
  addresses = ["ceos-02:50051"]
  username = "${NETWORK_AGENT_USER}"
  password = "${NETWORK_AGENT_PASSWORD}"
  redial = "20s"
  # Exclude the "path" tag from the output
  tagexclude = ["path"]

  [[inputs.gnmi.subscription]]
    name = "interface"
    path = "/interfaces/interface/state/counters"
    subscription_mode = "sample"
    sample_interval = "10s"

  [[inputs.gnmi.subscription]]
    name = "interface"
    path = "/interfaces/interface/state/oper-status"
    subscription_mode = "sample"
    sample_interval = "10s"

[[processors.rename]]
  # Rename the tag "source" to "device"
  [[processors.rename.replace]]
    tag = "source"
    dest = "device"

# Add a tag "intf_role" dynamically by querying Nautobot
[[processors.execd]]
  # Make sure to only pass the "interface" measurement netrics to the script
  namepass = ["interface"]
  # Run the Nautobot data enrichment script
  command = ["python", "/etc/telegraf/script.py"]
  # If script quits unexpectedly, wait 10 seconds before restarting
  restart_delay = "10s"

[[outputs.file]]
  files = ["stdout"]