---
groups:
  - name: Host Down
    rules:
      - alert: HostDown
        expr: net_response_result_code{} != 0
        for: 1m
        labels:
          severity: critical
          source: stack
          environment: Production
        annotations:
          summary: "Host is down"
          description: "Host <{{ $labels.device }}> is down!"

  - name: Job Down
    rules:
      - alert: JobDown
        expr: up{job=~"telegraf.*"} == 0
        for: 30s
        labels:
          severity: critical
          source: stack
          environment: Production
        annotations:
          summary: "Job is down"
          description: "Job <{{ $labels.job }}> is down!"
