---
networks:
  network-observability:
    external: true
    name: network-observability

volumes:
  nautobot_postgres_data:

services:

  telegraf-01:
    image: docker.io/networktocode/network-agent:1.27-py3.8-v0.4.2-v0.3.10
    command: telegraf --config /etc/telegraf/telegraf.conf
    tty: true
    volumes:
      - ./configs/telegraf/telegraf-01.conf.toml:/etc/telegraf/telegraf.conf
    ports:
      - 9004:9004
    env_file:
      - ../../.env
    depends_on:
      kafka-01:
        condition: service_healthy
    networks:
      - network-observability

  telegraf-02:
    image: docker.io/networktocode/network-agent:1.27-py3.8-v0.4.2-v0.3.10
    command: telegraf --config /etc/telegraf/telegraf.conf
    tty: true
    volumes:
      - ./configs/telegraf/telegraf-02.conf.toml:/etc/telegraf/telegraf.conf
      - ./configs/telegraf/script.py:/etc/telegraf/script.py
    ports:
      - 9005:9005
    env_file:
      - ../../.env
    networks:
      - network-observability

  telegraf-consumer:
    image: docker.io/networktocode/network-agent:1.27-py3.8-v0.4.2-v0.3.10
    command: telegraf --config /etc/telegraf/telegraf.conf
    tty: true
    volumes:
      - ./configs/telegraf/telegraf-consumer.conf.toml:/etc/telegraf/telegraf.conf
    ports:
      - 9006:9006
    env_file:
      - ../../.env
    depends_on:
      kafka-01:
        condition: service_healthy
    networks:
      - network-observability

  logstash:
    image: docker.io/grafana/logstash-output-loki:main
    command: -f /home/logstash/logstash.cfg
    volumes:
      - ./configs/logstash/logstash.cfg:/home/logstash/logstash.cfg
    ports:
      - 1515:1515
    environment:
      XPACK_MONITORING_ENABLED: false
    env_file:
      - ../../.env
    networks:
      - network-observability

  nautobot:
    image: "networktocode/nautobot:2.1-py3.10"
    env_file:
      - "../../.env"
    ports:
      - "8443:8443"
      - "8080:8080"
    restart: "unless-stopped"
    volumes:
      - ./configs/nautobot/nautobot_config.py:/opt/nautobot/nautobot_config.py
    networks:
      - network-observability

  nautobot-redis:
    image: "redis:alpine"
    command:
      - "sh"
      - "-c"
      - "redis-server --appendonly yes --requirepass $$NAUTOBOT_REDIS_PASSWORD"
    restart: "unless-stopped"
    env_file:
      - ../../.env
    networks:
      - network-observability

  nautobot-postgres:
    image: "postgres:14"
    environment:
      NAUTOBOT_DB_ENGINE: "django.db.backends.postgres"
      POSTGRES_USER: ${NAUTOBOT_POSTGRES_USER}
      POSTGRES_PASSWORD: ${NAUTOBOT_POSTGRES_PASSWORD}
      POSTGRES_DB: ${NAUTOBOT_POSTGRES_DB}
    volumes:
      - nautobot_postgres_data:/var/lib/postgresql/data
    restart: "unless-stopped"
    env_file:
      - ../../.env
    networks:
      - network-observability

  zookeeper-01:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
    networks:
      - network-observability

  kafka-01:
    image: confluentinc/cp-kafka:latest
    hostname: kafka-01
    depends_on:
      - zookeeper-01
    ports:
      - 9092:9092
      - 29092:29092
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 9092 || exit 1"]
      start_period: 10s
      interval: 5s
      timeout: 10s
      retries: 20
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-01:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-01:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - network-observability

  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - 9080:9080
    depends_on:
      - kafka-01
    environment:
      SERVER_PORT: 9080
      KAFKA_CLUSTERS_0_NAME: telegraf-pipeline
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka-01:29092
    networks:
      - network-observability