name: Build and Push Dev Container

on:
  push:
    branches:
      - main

jobs:
  netobs-devcontainer:
    # permissions: write-all
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log into registry ghcr.io
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GH_TOKEN }}

    - name: Build and push devcontainer image
      uses: devcontainers/ci@v0.3
      with:
        imageName: ghcr.io/network-observability/netobs-devcontainer
        imageTag: latest
        # cacheFrom: ghcr.io/network-observability/netobs-devcontainer
        # tags: yourusername/yourrepository:tag  # Replace with your Docker image tag
        push: always
